{
    'name': 'OdooEduConnect',
    'version': '1.0.1',
    'category': 'Tools',
    'summary': 'Módulo de gestión educativa',
    'author': 'Javier Herrera',
    'website': 'https://github.com/JH1018/Modulo_Odoo8',
    'depends': ['base'],
    'data': [
        'security/security.xml',
        'security/student_rules.xml',
        'security/ir.model.access.csv',
        
        'views/exam/searchExam.xml',
        'views/exam/registerExamView.xml',
        'views/exam/tree_exam.xml',
        'views/teacher/searchRegisterView.xml',
        'views/teacher/tree_teacher.xml',
        'views/teacher/registerTeacherView.xml',
        'views/students/searchView.xml',
        'views/students/tree_student.xml',
        'views/students/registerView.xml',
        'views/grades/searchGradesView.xml',
        'views/grades/tree_grades.xml',
        'views/grades/registerGradesView.xml',
        'views/subject/searchRegisterView.xml',
        'views/subject/tree_subject.xml',
        'views/subject/registerSubjectView.xml',
        'views/room/searchRoomView.xml',
        'views/room/tree_room.xml',
        'views/room/registerRoomView.xml',
        'views/menu.xml',
        'wizard/student_export_wizard_view.xml',
        'wizard/teacher_export_wizard_view.xml',
        'wizard/subject_export_wizard_view.xml',
        'wizard/grade_export_wizard_view.xml',
        'wizard/room_export_wizard_view.xml',
    ],
    'installable': True,
    'auto_install': False,
    'external_dependencies': {
        'python': ['reportlab'],
    },
}
